Add functions for replicate, publish and deprecate
SUSE-Enceladus/aliyun-img-utils pull request #16
Opened 2021-03-11 22:20 UTC by smarlowucf

- Add method to activate deprecated images
- Add option to get image by name or id.
- Add comments to CLI functions.
- Log error in helper methods instead of failing in on region.

@rjschwei sorry this grew bigger than planned. But most of the functions do pretty much the same thing with slightly different attrs.

2021-03-12 22:02 UTC, rjschwei requested changes
Just a few things. I think the logging w.r.t. what methods in the API are public is inconsistent. Hope the comment in the deprecation case makes sense. It applies to the other cases as well.

Looks good over all.

2021-03-12 22:31 UTC, smarlowucf commented on aliyun_img_utils/aliyun_image.py
> +                self.log.info(f'{image_id} created in {region}')
Ack

2021-03-12 22:42 UTC, smarlowucf commented on aliyun_img_utils/aliyun_image.py
> +            )
I like both being in the public API as they each are useful. I think the return values and logging can be consistent. The helper loops would return a hash of the values returned from the base methods.

2021-03-12 22:49 UTC, smarlowucf commented on aliyun_img_utils/aliyun_image.py
> +        request.set_LaunchPermission('HIDDEN')
Ack, then this would be a required arg `--launch-permission`

2021-03-13 01:04 UTC, smarlowucf commented on aliyun_img_utils/aliyun_image.py
> +            )
Changes made but not sure if I follow after re-reading the comments.

2021-03-15 11:52 UTC, rjschwei approved these changes

2021-03-15 11:52 UTC, merged