Start cli module.
SUSE-Enceladus/aliyun-img-utils pull request #3
Opened 2020-12-14 17:30 UTC by smarlowucf

Add delete and upload image tarball commands.

2020-12-15 10:45 UTC, jgleissner approved these changes

2021-01-07 21:10 UTC, rjschwei requested changes

2021-01-07 21:10 UTC, rjschwei commented on aliyun_img_utils/aliyun_utils.py
> +    Update the module level progress bar with image download progress.
s/download/upload/ ?

2021-01-13 16:01 UTC, smarlowucf commented on aliyun_img_utils/aliyun_cli.py
> +        uploader = AliyunImage(
image shadows another variable, went with `aliyun_image`.

2021-01-13 16:10 UTC, smarlowucf commented on aliyun_img_utils/aliyun_cli.py
> +        deleted = uploader.delete_image_tarball(blob_name, **keyword_args)
Right, this is my intention but I have no framework image functions yet. So my plan was to update the CLI function similar to the suggestion once we have a delete_image function.

2021-01-13 16:26 UTC, smarlowucf commented
@rjschwei updated per comments. The delete function I plan to change similar to your suggestions once we have the image level functions in place.

2021-01-20 19:22 UTC, rjschwei approved these changes

2021-01-20 19:22 UTC, merged